spring:
  profiles: login
  datasource:
    url: jdbc:postgresql://localhost:5432/test3
    username: postgres
    password: keyport01
    driverClassName: org.postgresql.Driver
    session-timeout: 60
  jpa:
    hibernate:
      ddl-auto: create-drop